ARG BASE_IMAGE=ros:humble
FROM $BASE_IMAGE

ARG USERNAME
ARG USER_UID
ARG USER_GID
ARG TARGET_PLATFORM
ENV USER=${USERNAME}
ENV TARGET_PLATFORM=${TARGET_PLATFORM}

# Delete user if it exists in container
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Ensure no expired keys
RUN apt-get update || true \
 && apt-get install -y --no-install-recommends curl gnupg2 ca-certificates \
 && curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    | gpg --batch --yes --no-tty --dearmor \
      -o /usr/share/keyrings/ros-archive-keyring.gpg \
 && echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
    http://packages.ros.org/ros2/ubuntu jammy main" \
    > /etc/apt/sources.list.d/ros2.list

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Prepare installation and work environment
WORKDIR /home/${USERNAME}/roboboat_ws
COPY requirements.txt .
COPY apt-packages.txt .
COPY package-ignore.txt .
COPY package_clean.sh .

RUN ./package_clean.sh

# Install all apt packages
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y \
       python3-pip \
       python3-venv \
       build-essential \
    && grep -vFf package-ignore.txt apt-packages.txt | xargs apt-get -y install --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Virtualize and install Python packages
RUN python3 -m venv --system-site-packages /workspace/venv \
    && /workspace/venv/bin/pip install --upgrade pip \
    && /workspace/venv/bin/pip install --no-cache-dir -r requirements.txt

ENV PATH=/workspace/venv/bin:$PATH
ENV SHELL=/bin/bash

USER $USERNAME
CMD ["/bin/bash"]
