services:
  dev:
    image: ${ASTRO_IMAGE:-lunarzdev/astro:core}
    volumes:
      - ${PWD}:/home/roboboat/roboboat_ws:z
      - /dev:/dev
      - /sys:/sys:rw
  sitl:
    volumes:
      - /dev:/dev
