#!/usr/bin/env python3
"""Resolve a vcs .repos manifest's moving Git refs to exact commits."""

from __future__ import annotations

import argparse
import concurrent.futures
import re
import subprocess
import sys
import urllib.request

import yaml


SHA = re.compile(r"^[0-9a-f]{40}$")

# Jazzy's core ros2.repos intentionally does not contain every released ROS
# package. Keep packages required by this image here so regenerating the lock
# cannot silently remove them.
EXTRA_REPOSITORIES = {
    "ros-perception/vision_msgs": {
        "type": "git",
        "url": "https://github.com/ros-perception/vision_msgs.git",
        "version": "jazzy",
    },
    "ros-tooling/topic_tools": {
        "type": "git",
        "url": "https://github.com/ros-tooling/topic_tools.git",
        "version": "jazzy",
    },
}


def read_manifest(source: str) -> dict:
    if source.startswith(("https://", "http://")):
        with urllib.request.urlopen(source) as response:  # noqa: S310 - explicit CLI input
            return yaml.safe_load(response)
    with open(source, encoding="utf-8") as stream:
        return yaml.safe_load(stream)


def resolve(item: tuple[str, dict]) -> tuple[str, dict]:
    name, repository = item
    repository = dict(repository)
    version = str(repository["version"])
    if SHA.fullmatch(version):
        return name, repository

    output = subprocess.run(
        [
            "git",
            "ls-remote",
            repository["url"],
            f"refs/heads/{version}",
            f"refs/tags/{version}",
            f"refs/tags/{version}^{{}}",
        ],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.splitlines()
    refs = {ref: commit for commit, ref in (line.split() for line in output)}
    commit = (
        refs.get(f"refs/tags/{version}^{{}}")
        or refs.get(f"refs/tags/{version}")
        or refs.get(f"refs/heads/{version}")
    )
    if not commit:
        raise RuntimeError(f"Cannot resolve {name}: {version}")
    repository["version"] = commit
    return name, repository


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source")
    parser.add_argument("output")
    parser.add_argument("--workers", type=int, default=12)
    args = parser.parse_args()

    manifest = read_manifest(args.source)
    repositories = manifest["repositories"]
    for name, repository in EXTRA_REPOSITORIES.items():
        repositories.setdefault(name, repository)
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
        locked = dict(pool.map(resolve, repositories.items()))

    with open(args.output, "w", encoding="utf-8") as stream:
        stream.write("# Generated by .devcontainer/lock-repos.py; review updates before committing.\n")
        yaml.safe_dump({"repositories": locked}, stream, sort_keys=False)
    print(f"Locked {len(locked)} repositories in {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
